import AdminShell from "@/components/admin/AdminShell";
import SubmitButton from "@/components/admin/SubmitButton";
import DeleteButton from "@/components/admin/DeleteButton";
import AssetUpload from "@/components/admin/AssetUpload";
import { deleteCourse, saveCourse } from "../actions";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type Course={id:number;name:string;description:string;price:number|null;hours:number|null;status:string;image_url:string|null;sort_order:number};
function CourseForm({course}:{course?:Course}){return <form action={saveCourse} className="admin-card space-y-4">{course&&<input type="hidden" name="id" value={course.id}/>}<label className="admin-label">اسم الدورة<input name="name" required defaultValue={course?.name} className="admin-input"/></label><label className="admin-label">الوصف<textarea name="description" rows={3} defaultValue={course?.description} className="admin-input"/></label><div className="grid grid-cols-2 gap-3"><label className="admin-label">السعر<input name="price" type="number" min="0" step="0.01" defaultValue={course?.price ?? ""} className="admin-input"/></label><label className="admin-label">الساعات<input name="hours" type="number" min="0" defaultValue={course?.hours ?? ""} className="admin-input"/></label></div><label className="admin-label">الحالة<select name="status" defaultValue={course?.status || "available"} className="admin-input"><option value="available">متاحة</option><option value="coming_soon">قريبًا</option><option value="hidden">مخفية</option></select></label><label className="admin-label">رابط الصورة<input name="image_url" type="url" defaultValue={course?.image_url || ""} className="admin-input"/></label><label className="admin-label">الترتيب<input name="sort_order" type="number" defaultValue={course?.sort_order || 0} className="admin-input"/></label><div className="flex gap-3"><SubmitButton label={course?"حفظ التعديل":"إضافة الدورة"}/><button type="reset" className="admin-secondary">إلغاء</button>{course&&<DeleteButton action={deleteCourse}/>}</div></form>}
export default async function CoursesPage(){await requireAdmin();const supabase=await createClient();const{data}=await supabase.from("courses").select("*").order("sort_order");return <AdminShell><h1 className="text-3xl font-black">إدارة الدورات</h1><div className="mt-8 grid gap-6 xl:grid-cols-2"><CourseForm/>{(data ?? []).map(course=><CourseForm key={course.id} course={course}/>)}</div><div className="mt-8 max-w-xl"><AssetUpload/></div></AdminShell>}
